package com.daobao.asus.greendaodemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.daobao.asus.greendaodemo.greendao.dayStep;
import com.daobao.asus.greendaodemo.greendao.Sport;

import com.daobao.asus.greendaodemo.greendao.dayStepDao;
import com.daobao.asus.greendaodemo.greendao.SportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayStepDaoConfig;
    private final DaoConfig sportDaoConfig;

    private final dayStepDao dayStepDao;
    private final SportDao sportDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayStepDaoConfig = daoConfigMap.get(dayStepDao.class).clone();
        dayStepDaoConfig.initIdentityScope(type);

        sportDaoConfig = daoConfigMap.get(SportDao.class).clone();
        sportDaoConfig.initIdentityScope(type);

        dayStepDao = new dayStepDao(dayStepDaoConfig, this);
        sportDao = new SportDao(sportDaoConfig, this);

        registerDao(dayStep.class, dayStepDao);
        registerDao(Sport.class, sportDao);
    }
    
    public void clear() {
        dayStepDaoConfig.clearIdentityScope();
        sportDaoConfig.clearIdentityScope();
    }

    public dayStepDao getDayStepDao() {
        return dayStepDao;
    }

    public SportDao getSportDao() {
        return sportDao;
    }

}
