package com.daobao.asus.greendaodemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayStepDaoConfig;

    private final dayStepDao dayStepDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayStepDaoConfig = daoConfigMap.get(dayStepDao.class).clone();
        dayStepDaoConfig.initIdentityScope(type);

        dayStepDao = new dayStepDao(dayStepDaoConfig, this);

        registerDao(dayStep.class, dayStepDao);
    }
    
    public void clear() {
        dayStepDaoConfig.clearIdentityScope();
    }

    public dayStepDao getDayStepDao() {
        return dayStepDao;
    }

}
